#######################################################################################
# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
title: "Octosport Documentation"
author: Theodosios Athanasakis
description: Official documentation of Octosport software.
copyright: Octosport 2025
logo: images/octopus.png
exclude_patterns: [ _build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints" ]
only_build_toc_files: true

#######################################################################################
# Execution Settings
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  cache: ""
  exclude_patterns: [ ]
  timeout: 30
  run_in_temp: false
  allow_errors: false
  stderr_output: show

#######################################################################################
# Parse and Render Settings
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence # To allow for ::: instead of ``` blocks.
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [ mailto, http, https ]
  myst_dmath_double_inline: true

#######################################################################################
# HTML-Specific Settings
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "images/favicon.ico"
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  use_multitoc_numbering: true
  extra_navbar: Powered by Octosport
  extra_footer: ""
#  google_analytics_id: ""
  home_page_in_navbar: true
  baseurl: ""
  comments:
    hypothesis: false
    utterances: false
  announcement: "Under Development"

#######################################################################################
# LaTeX-Specific Settings
# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true
  latex_documents:
    targetname: book.tex

#######################################################################################
# Launch Button Settings
launch_buttons:
  notebook_interface : classic

#######################################################################################
# Information about where the book exists on the web
#repository:
#  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)


#######################################################################################
# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

#######################################################################################
# Advanced and power-user settings
sphinx:
#  extra_extensions: # [...]
#  local_extensions: # [...]
  recursive_update: false
#  config: # [...]
